[env]
CPAL_ASIO_DIR = { value = "./../.asio", relative = true }
LIBCLANG_WINDOWS_PATH = { value = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\Llvm\\x64\\lib", relative = false }
LIBCLANG_PATH = { value = "/opt/homebrew/opt/llvm/lib", relative = false }
