---
kind: pipeline
type: docker
name: build-amd64-jammy

platform:
  arch: amd64

steps:
  - name: "Rust"
    image: ubuntu:22.04
    when:
      event:
        - push
        - tag
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin"
    commands:
      - apt update
      - apt install curl libsodium-dev build-essential libc6-amd64-cross libc6-dev-amd64-cross libc6-arm64-cross libc6-dev-arm64-cross gcc-x86-64-linux-gnu gcc-aarch64-linux-gnu ca-certificates -y --no-install-recommends
      - curl https://sh.rustup.rs -sSf | sh -s -- -y
      - cd pack$HOME/.cargo/bin/cargo run package
  - name: Pack Setup
    depends_on:
      - "Rust"
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_API_KEY
      files: alaydriem_ll_*.mcpack
      prerelease: true
      title: ${DRONE_TAG}
      overwrite: true
    when:
      event: tag
