import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// The marketing page owns `/`. Starlight owns `/wiki/**` via routeBasePath.
// Both pull their colours and type scale from the same src/styles/tokens.css,
// so the wiki cannot drift away from the site.
export default defineConfig({
  site: 'https://www.bedrockvoicechat.com',
  integrations: [
    // Starlight injects a root [...slug] route and derives each URL from the
    // file's path under src/content/docs. Nesting the docs in a `wiki/` folder
    // is therefore what puts them on /wiki/**; there is no base-path option to
    // set (routeBasePath was removed in 0.41). The marketing page keeps `/`
    // because a static route in src/pages outranks an injected dynamic one.
    starlight({
      title: 'BVC Wiki',
      description: 'Setup guides, configuration reference and troubleshooting for Bedrock Voice Chat.',
      favicon: '/favicon.svg',
      customCss: ['./src/styles/starlight.css'],
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/Alaydriem/bedrock-voice-chat' },
        { icon: 'discord', label: 'Discord', href: 'https://discord.gg/CdtchD5zxr' },
      ],
      // The docs live on gh-pages-src, not on a code branch, so "Edit this page"
      // has to point there or it lands on a 404.
      editLink: {
        baseUrl:
          'https://github.com/Alaydriem/bedrock-voice-chat/edit/gh-pages-src/src/content/docs/wiki/',
      },
      // Autogenerated from the directory tree: adding a page means creating the
      // file, nothing more. Order within a group comes from `sidebar.order` in
      // each page's frontmatter, falling back to alphabetical.
      sidebar: [
        { label: 'Getting started', items: [{ autogenerate: { directory: 'wiki/start' } }] },
        { label: 'Running a server', items: [{ autogenerate: { directory: 'wiki/server' } }] },
        { label: 'Integrations', items: [{ autogenerate: { directory: 'wiki/integrations' } }] },
      ],
    }),
  ],
});
