import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// The marketing page owns `/`. Starlight owns `/wiki/**` via routeBasePath.
// Both pull their colours and type scale from the same src/styles/tokens.css,
// so the wiki cannot drift away from the site.
export default defineConfig({
  site: 'https://www.bedrockvoicechat.com',
  integrations: [
    // Starlight injects a root [...slug] route and derives each URL from the
    // file's path under src/content/docs. Nesting the docs in a `wiki/` folder
    // is therefore what puts them on /wiki/**; there is no base-path option to
    // set (routeBasePath was removed in 0.41). The marketing page keeps `/`
    // because a static route in src/pages outranks an injected dynamic one.
    starlight({
      title: 'BVC Wiki',
      description: 'Setup guides, configuration reference and troubleshooting for Bedrock Voice Chat.',
      favicon: '/favicon.svg',
      customCss: ['./src/styles/starlight.css'],
      // Adds <link rel="alternate" type="text/markdown"> so an agent landing on
      // any page can find its raw-markdown twin without knowing the convention.
      components: { Head: './src/components/Head.astro' },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/Alaydriem/bedrock-voice-chat' },
        { icon: 'discord', label: 'Discord', href: 'https://discord.gg/CdtchD5zxr' },
      ],
      // The docs live on gh-pages-src, not on a code branch, so "Edit this page"
      // has to point there or it lands on a 404.
      editLink: {
        baseUrl:
          'https://github.com/Alaydriem/bedrock-voice-chat/edit/gh-pages-src/src/content/docs/wiki/',
      },
      // Autogenerated from the directory tree: adding a page means creating the
      // file, nothing more. Order within a group comes from `sidebar.order` in
      // each page's frontmatter, falling back to alphabetical.
      // Groups without subdirectories autogenerate: adding a page there means
      // creating the file and setting `sidebar.order` in its frontmatter.
      //
      // `player` and `server` are listed explicitly because autogenerate emits
      // every subdirectory as a group BEFORE the leaf pages, regardless of the
      // order set on the directory's index. That put "Java mod" above
      // "Installation" and buried each section's Overview under its children.
      // Reading order matters more here than config brevity.
      sidebar: [
        // The wiki root is not inside any autogenerated directory, so it needs
        // an explicit entry or /wiki/ is unreachable from the nav.
        { label: 'What is BVC?', link: '/wiki/' },
        { label: 'Start here', items: [{ autogenerate: { directory: 'wiki/start' } }] },
        {
          label: 'For players',
          items: [
            'wiki/player',
            'wiki/player/signing-in',
            'wiki/player/using-voice-chat',
            'wiki/player/groups',
            'wiki/player/chat',
            {
              label: 'In-game commands',
              items: [
                'wiki/player/in-game-commands',
                'wiki/player/in-game-commands/bedrock',
                'wiki/player/in-game-commands/java',
              ],
            },
            'wiki/player/using-the-jukebox',
            'wiki/player/audio-library',
            'wiki/player/settings',
            'wiki/player/parents-and-age',
            'wiki/player/troubleshooting',
          ],
        },
        {
          label: 'Running a server',
          items: [
            'wiki/server',
            'wiki/server/installation',
            'wiki/server/tls',
            'wiki/server/docker',
            'wiki/server/bedrock-addon',
            'wiki/server/beta-apis',
            'wiki/server/nonet-addon',
            {
              label: 'Java mod',
              items: [
                'wiki/server/java-mod',
                'wiki/server/java-mod/fabric',
                'wiki/server/java-mod/papermc',
              ],
            },
            'wiki/server/players-and-permissions',
            'wiki/server/privacy-and-telemetry',
            'wiki/server/monitoring',
            'wiki/server/troubleshooting',
          ],
        },
        { label: 'Where BVC works', items: [{ autogenerate: { directory: 'wiki/platforms' } }] },
        { label: 'Streaming & recording', items: [{ autogenerate: { directory: 'wiki/creator' } }] },
        { label: 'Reference', items: [{ autogenerate: { directory: 'wiki/reference' } }] },
      ],
    }),
  ],

  // The GitHub wiki used one flat page per Discord question, and those URLs are
  // linked from Discord threads and indexed. Every retired name maps to wherever
  // its content now lives, including the pages that were merged into another.
  redirects: {
    '/wiki/Home': '/wiki/',
    '/wiki/How-to-Download-Bedrock-Voice-Chat': '/wiki/start/downloads/',
    '/wiki/Android-App': '/wiki/start/downloads/',
    '/wiki/iOS-App': '/wiki/start/downloads/',
    '/wiki/Discussions---Question': '/wiki/start/report-an-issue/',
    '/wiki/Public-Server-Directory': '/wiki/start/faq/',
    '/wiki/Simple-Voice-Chat-Integration': '/wiki/start/faq/',
    '/wiki/How-You-Can-Support-Bedrock-Voice-Chat': '/wiki/start/supporting-bvc/',

    '/wiki/Logging-In-to-Bedrock-Voice-Chat-Client': '/wiki/player/signing-in/',
    '/wiki/Login-URL': '/wiki/player/signing-in/',
    '/wiki/Managing-Player-Audio': '/wiki/player/using-voice-chat/',
    '/wiki/Groups': '/wiki/player/groups/',
    '/wiki/Settings': '/wiki/player/settings/',
    '/wiki/Age-Signals-&-Declared-Age-Ranges': '/wiki/player/parents-and-age/',

    '/wiki/BVC-Server-Installation': '/wiki/server/installation/',
    '/wiki/BDS-Server-Pack-Installation': '/wiki/server/bedrock-addon/',
    '/wiki/Minecraft-Java-Support': '/wiki/server/java-mod/',

    '/wiki/Bedrock-Realms-Support': '/wiki/platforms/realms/',
    '/wiki/Aternos-Support': '/wiki/platforms/aternos/',
    '/wiki/Geyser-Support': '/wiki/platforms/geyser/',
    '/wiki/Mobile-and-Console-Support': '/wiki/platforms/console-and-mobile/',
    '/wiki/LAN-World-Support': '/wiki/platforms/lan-and-local-worlds/',
    '/wiki/Local-and-Self-Hosted-Worlds': '/wiki/platforms/lan-and-local-worlds/',

    '/wiki/Recording': '/wiki/creator/recording/',
    '/wiki/Stream-Deck-App': '/wiki/creator/stream-deck/',
    '/wiki/Websocket-API': '/wiki/creator/websocket-api/',

    '/wiki/Command-Line-Interface': '/wiki/reference/cli/',
  },
});
