# Cross configuration for cross-compilation
[target.aarch64-unknown-linux-gnu]
# Use a custom Docker image that includes OpenSSL development libraries
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.aarch64-unknown-linux-gnu.env]
# Configure OpenSSL for cross-compilation
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDORED",
    "PKG_CONFIG_ALLOW_CROSS",
]