use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, export_to = "./../../client/src/js/bindings/")]
pub enum AnalyticsEvent {
    AppStarted,
    AppExited,
    Reload,
    AudioDeviceChanged,
    JavaIdentityLinked,
    RecordingExported,
    Logout,
    LoginCompleted,
    ServerChanged,
    AnalyticsToggled,
    OnboardingCompleted,
    NoiseGateToggled,
    VoiceModeChanged,
    WebsocketServerToggled,
    ChannelJoined,
    ChannelLeft,
    RecordingStarted,
    RecordingStopped,
    MinecraftProtocolAllowed,
    MinecraftProtocolRejected,
    BedrockProxyStarted,
    BedrockRealmStarted,
    BedrockConnected,
    BedrockDisconnected,
    IapPurchaseStarted,
    IapPurchaseCompleted,
    IapPurchaseFailed,
    IapRestoreInvoked,
    DiscordAccountLinked,
    DiscordAccountUnlinked,
    DiscordAccountResynced,
    FlagsmithFlagsFetched,
    ClientLinkQuality,
    LoginShown,
    DashboardReached,
    ServerSelected,
    OnboardingShown,
    NoServerClicked,
    WikiCtaClicked,
    HostingCtaClicked,
    // Voice arrived: the first time in a session that audio from another player reached
    // this client. The end of the funnel, and the only step in it no amount of UI can
    // fake — every earlier event says someone got somewhere, this one says it worked.
    Activated,
}

impl AnalyticsEvent {
    pub fn name(&self) -> &'static str {
        match self {
            Self::AppStarted => "AppStarted",
            Self::AppExited => "AppExited",
            Self::Reload => "Reload",
            Self::AudioDeviceChanged => "AudioDeviceChanged",
            Self::JavaIdentityLinked => "JavaIdentityLinked",
            Self::RecordingExported => "RecordingExported",
            Self::Logout => "Logout",
            Self::LoginCompleted => "LoginCompleted",
            Self::ServerChanged => "ServerChanged",
            Self::AnalyticsToggled => "AnalyticsToggled",
            Self::OnboardingCompleted => "OnboardingCompleted",
            Self::NoiseGateToggled => "NoiseGateToggled",
            Self::VoiceModeChanged => "VoiceModeChanged",
            Self::WebsocketServerToggled => "WebsocketServerToggled",
            Self::ChannelJoined => "ChannelJoined",
            Self::ChannelLeft => "ChannelLeft",
            Self::RecordingStarted => "RecordingStarted",
            Self::RecordingStopped => "RecordingStopped",
            Self::MinecraftProtocolAllowed => "MinecraftProtocolAllowed",
            Self::MinecraftProtocolRejected => "MinecraftProtocolRejected",
            Self::BedrockProxyStarted => "BedrockProxyStarted",
            Self::BedrockRealmStarted => "BedrockRealmStarted",
            Self::BedrockConnected => "BedrockConnected",
            Self::BedrockDisconnected => "BedrockDisconnected",
            Self::IapPurchaseStarted => "IapPurchaseStarted",
            Self::IapPurchaseCompleted => "IapPurchaseCompleted",
            Self::IapPurchaseFailed => "IapPurchaseFailed",
            Self::IapRestoreInvoked => "IapRestoreInvoked",
            Self::DiscordAccountLinked => "DiscordAccountLinked",
            Self::DiscordAccountUnlinked => "DiscordAccountUnlinked",
            Self::DiscordAccountResynced => "DiscordAccountResynced",
            Self::FlagsmithFlagsFetched => "FlagsmithFlagsFetched",
            Self::ClientLinkQuality => "ClientLinkQuality",
            Self::LoginShown => "LoginShown",
            Self::DashboardReached => "DashboardReached",
            Self::ServerSelected => "ServerSelected",
            Self::OnboardingShown => "OnboardingShown",
            Self::NoServerClicked => "NoServerClicked",
            Self::WikiCtaClicked => "WikiCtaClicked",
            Self::HostingCtaClicked => "HostingCtaClicked",
            Self::Activated => "Activated",
        }
    }
}
