[package]
name = "bedrock-voice-chat"
authors = ["Charles R. Portwood II <charlesportwoodii@erianna.com>"]
description = "Bedrock Voice Chat for Minecraft Bedrock"
repository = "https://github.com/alaydriem/bedrock-voice-chat"
version = "0.0.1"
edition = "2021"

[lib]
name = "pack"