pub(crate) mod about;
pub(crate) mod analytics;
pub(crate) mod audio;
pub(crate) mod audio_library;
#[cfg(feature = "bedrock-protocol")]
pub(crate) mod bedrock;
pub(crate) mod chat;
pub(crate) mod diagnostics;
pub(crate) mod discord;
pub(crate) mod env;
pub(crate) mod event;
pub(crate) mod feature_flags;
pub(crate) mod groups;
pub(crate) mod i18n;
pub(crate) mod iap;
pub(crate) mod keybinds;
pub(crate) mod keyring;
pub(crate) mod network;
pub(crate) mod players;
pub(crate) mod recordings;
#[cfg(desktop)]
pub(crate) mod updater;
pub(crate) mod websocket;
