# Mod Properties
modVersion=1.0.519
mavenGroup=com.alaydriem
archivesBaseName=bedrock-voice-chat

# Gradle Settings
org.gradle.jvmargs=-Xmx2G --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
org.gradle.parallel=true
