/**
 * Source of truth for the BDS pack manifests.
 *
 * Manifests are build artifacts generated by manifest.js (ManifestBuilder) — they
 * are NOT committed static files. Two variants are produced, each a self-contained
 * behavior+resource pack pair with its own distinct UUID set:
 *
 *   full    - dedicated servers; uses @minecraft/server-net + server-admin (HTTP transport)
 *   no-net  - Realms / servers without server-net; positions advertised via in-game chat
 *
 * UUIDs are hardcoded and MUST remain stable across releases. The `full` set reuses
 * the original UUIDs so existing installs continue to update in place. Never regenerate.
 */
const UUIDS = {
  full: {
    bp: {
      header: '6fb24263-357a-407c-aebe-681f50b2de50',
      data: '335967ca-68cc-4043-984d-aaebf5881f2d',
      script: '5639bd17-70fd-4e7b-9947-5d3a70443ec1',
    },
    rp: {
      header: '20a36865-747e-4c38-8077-ea9228c2bd5d',
      resource: 'a7c2e3f1-9b4d-4e6a-8f1c-2d3e4f5a6b7c',
    },
  },
  'no-net': {
    bp: {
      header: '508a43ed-b95e-40cf-98eb-d78f2d72caa4',
      data: '640a4d16-aa4e-4bc4-906a-c5b22312e2c0',
      script: 'f83d2c44-4cf4-4a12-b909-ee6e7e378623',
    },
    rp: {
      header: '9a656a2e-defd-4f17-8b9d-011414c8abff',
      resource: 'bca3d7a3-841f-4a8f-a95b-b939fd713ea5',
    },
  },
};

const METADATA = {
  authors: ['Alaydriem'],
  product_type: 'addon',
};

const BP_MIN_ENGINE = [1, 26, 20];
const RP_MIN_ENGINE = [1, 26, 12];

const SCRIPT_ENTRY = 'scripts/main.js';

const BP_MODULE_DEPENDENCIES = [
  { version: '2.0.0', module_name: '@minecraft/server-ui' },
  { version: '2.9.0-beta', module_name: '@minecraft/server' },
  { version: '1.0.0-beta', module_name: '@minecraft/server-net' },
  { version: '1.0.0-beta', module_name: '@minecraft/server-admin' },
];

const VARIANTS = {
  full: {
    name: 'pack.name',
    description: 'pack.description',
    stripModules: [],
  },
  'no-net': {
    name: 'Bedrock Voice Chat (Realms + No-Net Servers)',
    description:
      'Bedrock Voice Chat for Realms and servers without @minecraft/server-net. v{version}',
    stripModules: ['@minecraft/server-net', '@minecraft/server-admin'],
  },
};

module.exports = {
  UUIDS,
  METADATA,
  BP_MIN_ENGINE,
  RP_MIN_ENGINE,
  SCRIPT_ENTRY,
  BP_MODULE_DEPENDENCIES,
  VARIANTS,
};
