// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";

export type AdminUserListQuery = { page: number | null, page_size: number | null, search: string | null, game: Game | null, };
