// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an admin mutation ended, for a caller that has to say something different about
 * each case.
 *
 * A typed answer rather than a status code flattened into an error string: the pane
 * distinguishes "you cannot ban yourself" from "the server is unreachable", and a string
 * comparison would break the moment the copy is translated. Modelled on
 * `CredentialVerdict`, which exists for the same reason.
 */
export type AdminActionOutcome = "applied" | "conflict" | "not_found" | "forbidden" | "invalid";
