// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalyticsEvent = "AppStarted" | "AppExited" | "Reload" | "AudioDeviceChanged" | "JavaIdentityLinked" | "RecordingExported" | "Logout" | "LoginCompleted" | "ServerChanged" | "AnalyticsToggled" | "OnboardingCompleted" | "NoiseGateToggled" | "VoiceModeChanged" | "WebsocketServerToggled" | "ChannelJoined" | "ChannelLeft" | "RecordingStarted" | "RecordingStopped";
