// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddonMode } from "./AddonMode";

export type ApiConfigBedrockServer = { name: string, host: string, port: number, protocol_version: number | null, addon_mode: AddonMode, };
