// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiConfigBedrockServer } from "./ApiConfigBedrockServer";

export type ApiConfigBedrock = { enabled: boolean, dns_enabled: boolean, transfer_port: number | null, servers: Array<ApiConfigBedrockServer>, };
