// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the server relays in-game chat.
 *
 * A server that predates this field sends nothing and reads as enabled, so an older
 * deployment never appears to have turned chat off.
 */
export type ApiConfigChat = { enabled: boolean, };
