// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the app may point the idle ring at players beyond voice range.
 *
 * A server that predates this field sends nothing and reads as enabled, so an older
 * deployment keeps the ring it always had.
 */
export type ApiConfigRadar = { enabled: boolean, };
