// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiConfigAge } from "./ApiConfigAge";
import type { ApiConfigBedrock } from "./ApiConfigBedrock";
import type { SpatialAudioConfig } from "./SpatialAudioConfig";

export type ApiConfigResponse = { status: string, client_id: string, protocol_version: string, quic_port: number, quic_ports: Array<number>, spatial_audio: SpatialAudioConfig, bedrock: ApiConfigBedrock, age: ApiConfigAge, };
