// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the server permits clients to record voice sessions.
 *
 * A server that predates this field sends nothing and reads as permitted, so an
 * older deployment never appears to have turned recording off.
 */
export type ApiConfigRecording = { enabled: boolean, };
