// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpatialAudioConfig } from "./SpatialAudioConfig";

export type ApiConfig = { status: string, client_id: string, protocol_version: string, spatial_audio: SpatialAudioConfig, };
