// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many concurrent voice sessions this server admits, and how many it holds now.
 *
 * A server that predates this field sends nothing and reads as unlimited, so an older
 * deployment never appears to be full.
 *
 * `in_use` is advisory. It can change between this probe and a connection attempt, and the
 * server's own admission check remains the authority.
 */
export type ApiConfigCapacity = { limit: number, in_use: number, };
