// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiError = { "error": "file_too_large", "detail": { max_bytes: bigint, } } | { "error": "audio_too_long", "detail": { max_duration_ms: bigint, } } | { "error": "invalid_format" } | { "error": "parse_failed" } | { "error": "not_found" } | { "error": "forbidden" } | { "error": "auth_failed" } | { "error": "duplicate" } | { "error": "internal" };
