// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppInfo = { app_version: string, protocol_version: string, build_commit: string, build_variant: string, build_number: string, };
