// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audio output format selection for rendering recordings
 */
export type AudioFormat = "Bwav" | "Mp4Opus";
