// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioDeviceType } from "./AudioDeviceType";
import type { StreamConfig } from "./StreamConfig";

export type AudioDevice = { io: AudioDeviceType, name: string, host: string, stream_configs: Array<StreamConfig>, display_name: string, };
