// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioDeviceType } from "./AudioDeviceType";

export type AudioDevice = { io: AudioDeviceType, name: string, };
