// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioFileListQuery = { page: number | null, page_size: number | null, sort_by: string | null, sort_order: string | null, search: string | null, };
