// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockConnectError = { "kind": "nethernet_rejected_no_fallback", bds_reason_code: number | null, bds_kick_message: string | null, } | { "kind": "bds_rejected_original_login", kick_message: string, } | { "kind": "bds_rejected_original_login_undecoded" } | { "kind": "handshake_other", message: string, } | { "kind": "auth", message: string, } | { "kind": "reauth_required" } | { "kind": "transport", message: string, } | { "kind": "other", message: string, };
