// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockStatus = { proxy_running: boolean, realms_running: boolean, xbox_authenticated: boolean, 
/**
 * The stored credential was rejected. The app should be showing a sign-in prompt.
 */
reauth_required: boolean, proxy_target_host: string | null, proxy_target_port: number | null, proxy_listen_port: number | null, proxy_started_at: bigint | null, active_realm_id: bigint | null, active_realm_name: string | null, 
/**
 * The name of the world this session is forwarding to, as the reader chose it in BVC
 * Connect — a resolved saved-or-advertised entry, or the host they typed.
 *
 * Worth carrying separately from the host: most worlds report a level name that identifies
 * nothing ("world", or a uuid from BDS, which cannot read one), so this is the only label a
 * person recognises. The app remembers it against the world's id.
 */
active_connection_name: string | null, };
