// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockStatus = { proxy_running: boolean, realms_running: boolean, xbox_authenticated: boolean, proxy_target_host: string | null, proxy_target_port: number | null, proxy_listen_port: number | null, proxy_started_at: bigint | null, active_realm_id: bigint | null, active_realm_name: string | null, };
