// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an attempt to mint fresh Xbox Live tokens from the stored credential ended.
 */
export type BedrockRenewal = { "kind": "renewed" } | { "kind": "unavailable", message: string, } | { "kind": "reauth_required" };
