// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockBackendKind } from "./BedrockBackendKind";

export type BedrockConnectionInfo = { local_address: string, lan_address: string, port: number, backend: BedrockBackendKind, remote_label: string, hive_dns_hostname: string, server_dns_enabled: boolean, server_transfer_relay: string | null, };
