// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockLogEntry = { timestamp_ms: bigint, level: string, target: string, message: string, };
