// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockConnectMode } from "./BedrockConnectMode";

export type BedrockConnectConfig = { mode: BedrockConnectMode, proxy_host: string | null, proxy_port: number | null, realm_id: bigint | null, network_interface: string | null, };
