// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelPlayer } from "./ChannelPlayer";

export type Channel = { id: string, name: string, players: Array<ChannelPlayer>, creator: string, };
