// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";

export type ChannelPlayer = { name: string, game: Game | null, gamerpic: string | null, };
