// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelEvents } from "./ChannelEvents";

export type ChannelEvent = { event: ChannelEvents, };
