// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which chat implementation is live for a world.
 *
 * Distinct from availability: this says whether a mod or the local proxy is the source of
 * chat, not whether chat works right now. A world can be `Server` mode with its chat channel
 * down, and the composer has to tell those apart.
 */
export type ChatMode = "Server" | "Local";
