// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which component carries a line composed in the app.
 *
 * Chosen from the world's declared addon mode and nothing else. Whether that addon is
 * answering right now is a separate question, answered by delivery itself: a mode is a
 * statement about which component owns chat, and it does not stop being true because a
 * server restarted or briefly went away.
 */
export type ChatTransport = "server" | "proxy_injection";
