// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A line the server refused, returned to the one connection that sent it.
 *
 * Carries the text back so the composer can settle the right pending line without the server
 * having to know anything about how the sender rendered it.
 */
export type ChatRejectedPacket = { reason: string, text: string, };
