// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatOrigin } from "./ChatOrigin";

/**
 * One line of in-game chat, travelling server to client.
 *
 * Nothing about this is stored. The app holds a bounded in-memory ring and the server holds
 * none at all, so the only history that exists is the one a client accumulated while connected.
 */
export type ChatMessagePacket = { 
/**
 * Absent for a server-authored line.
 */
author: string | null, text: string, 
/**
 * Absent on the no-net path, where the proxy session is the world and there is no key.
 */
world_uuid: string | null, origin: ChatOrigin, occurred_at_ms: bigint, };
