// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMode } from "./ChatMode";

/**
 * Whether chat can carry a message right now, and why not when it cannot.
 *
 * Deliberately a single answer covering every source rather than one flag per transport. A
 * proxy session and a mod reporting positions are two ways of reaching the same world, and
 * the composer only ever needs to know whether typing will accomplish anything.
 *
 * Polled rather than pushed: liveness has several independent inputs and a missed event on
 * any of them would leave the composer permanently wrong in one direction or the other.
 */
export type ChatAvailability = { available: boolean, 
/**
 * Which implementation is answering. `None` when nothing is.
 */
mode: ChatMode | null, 
/**
 * Shown in the composer when unavailable. Absent when chat works.
 */
reason: string | null, 
/**
 * The world's display name where one is known.
 */
world_name: string | null, };
