// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A line composed in the app, travelling client to server.
 *
 * Carries no author. The sender is the mTLS identity on the connection, resolved server-side;
 * trusting a body field here would let any client post as any player.
 */
export type ChatSendPacket = { 
/**
 * Absent on the no-net path, which has no world key and never reaches the server.
 */
world_uuid: string | null, text: string, };
