// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a send from the app did not go through.
 *
 * Shared rather than server-local because the sender is told: a refusal that only the server
 * knows about is indistinguishable, from the composer, from a message that landed.
 */
export type ChatRejection = "NoChannel" | { "WrongWorld": { current: string | null, } } | "NoWorld";
