// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a chat line came from.
 *
 * `Bridge` is the seam for a future Discord relay: nothing in the chat sync feature produces
 * it, but its presence means a bridge can be added without a wire change.
 */
export type ChatOrigin = "Game" | "App" | "Bridge";
