// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMode } from "./ChatMode";

/**
 * A world this player has been seen in, and whether chat works there right now.
 */
export type ChatWorld = { 
/**
 * Never rendered. A random UUID on the mod path and a derived hash on the proxy path,
 * polymorphic in length, and meaningless to a person either way.
 */
world_uuid: string, 
/**
 * The only user-facing label.
 */
world_name: string, last_seen: bigint, 
/**
 * The world is being hosted: position ingress is recent.
 */
active: boolean, 
/**
 * A mod chat channel is registered for it right now. A world can be active and
 * unavailable — positions flowing while the chat socket is down.
 */
available: boolean, mode: ChatMode, };
