// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sign-in code, and nothing else.
 *
 * The code row carries the player it was issued for, so the server already knows the
 * gamertag and the game before it reads anything from the request. Asking for the
 * gamertag alongside the code added no entropy — gamertags are public, the code is the
 * secret — while adding a way for a valid code to be rejected over a typo or a
 * difference in capitalisation.
 */
export type CodeLoginRequest = { code: string, };
