// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sign-in code, and nothing else.
 *
 * The code is the credential and the identifier both: its row carries the player it was
 * issued for, so the server resolves the gamertag and the game without being told
 * either. A gamertag alongside it would carry no secret — gamertags are public — and
 * could only disagree with what the code already says.
 */
export type CodeLoginRequest = { code: string, };
