// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscordLinkStatus = { configured: boolean, linked: boolean, role_count: number, last_synced: bigint | null, expired: boolean, };
