// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressFamily } from "./AddressFamily";
import type { ObservedCertificate } from "./ObservedCertificate";
import type { ReachabilityOutcome } from "./ReachabilityOutcome";

export type EndpointReachability = { addr: string, family: AddressFamily, port: number, outcome: ReachabilityOutcome, certificate: ObservedCertificate | null, };
