// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportFailure } from "./ExportFailure";

/**
 * What an export actually did.
 *
 * A render can fail per track while the others succeed, and a run that reports only
 * success hands somebody a folder with files missing from it and no way to know.
 */
export type ExportOutcome = { written: Array<string>, failed: Array<ExportFailure>, };
