// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportProgress = { session_id: string, track: string, index: number, total: number, };
