// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionHealth } from "./ConnectionHealth";

/**
 * Why the metrics stream is silent, or that it is not.
 *
 * The snapshot stream only publishes while a session is connected, so a subscriber watching for
 * loss sees frames simply stop when the link fails — which is the moment it most needs an
 * answer. This frame names the failure.
 *
 * A separate envelope rather than fields on the snapshot: a snapshot with zeroed measurements
 * renders as a flawless link with a 0 ms round trip, which misleads worse than no frame at all.
 */
export type HealthPush = { type: string, data: ConnectionHealth, };
