// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HytaleAuthStatus } from "./HytaleAuthStatus";
import type { LoginResponse } from "./LoginResponse";

/**
 * Response when polling Hytale device flow status
 */
export type HytaleDeviceFlowStatusResponse = { status: HytaleAuthStatus, login_response: LoginResponse | null, };
