// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a Hytale device flow authentication
 */
export type HytaleAuthStatus = "Pending" | "Success" | "Expired" | "Denied" | "Error";
