// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputLevel } from "./InputLevel";

/**
 * The unquantised capture level, for the screens that calibrate a microphone.
 *
 * Separate from `LevelsPush` because it carries a different measurement for a different
 * purpose: the meter scale is quantised to hold the message count down, and calibration needs
 * the amplitude that quantisation discards.
 */
export type InputLevelPush = { type: string, data: InputLevel, };
