// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proof that the push channel is still carrying, sent whether or not anything happened.
 *
 * The channel is otherwise silent by design: levels are published on change and never re-send
 * silence, and metrics and health only arrive while a session is connected. So a quiet channel
 * and a dead one look identical from the page, and the page is where that distinction has to be
 * drawn — a socket that Android suspended reports `readyState` 1 and delivers nothing, with no
 * close event to react to.
 *
 * Carries no data. Its arrival is the whole payload, which is why no consumer subscribes to it:
 * `EventChannel` times every frame it receives and this is the one that always comes.
 */
export type KeepalivePush = { type: string, };
