// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceMode } from "./VoiceMode";

export type KeybindConfig = { toggleMute: string, toggleDeafen: string, toggleRecording: string, pushToTalk: string, voiceMode: VoiceMode, };
