// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackEntry } from "./PackEntry";

export type LanguagePack = { v: number, locale: string, plural: Array<string>, m: { [key in string]: PackEntry }, };
