// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LevelSnapshot } from "./LevelSnapshot";

/**
 * Everyone's voice activity, as one push frame.
 */
export type LevelsPush = { type: string, data: LevelSnapshot, };
