// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParticipantLevel } from "./ParticipantLevel";

/**
 * Everyone's voice activity in one message.
 *
 * One message rather than two. The self level and the peer levels were separate events on
 * separate timers, each costing a webview delivery of its own, and on Android every delivery
 * is a unit of main-thread work — so two streams of them cost twice as much main thread for
 * information that is always read together.
 */
export type LevelSnapshot = { 
/**
 * This client's own microphone.
 */
own: ParticipantLevel, 
/**
 * Everyone audible, keyed by the name the roster uses.
 */
peers: { [key in string]: ParticipantLevel }, };
