// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressFamily } from "./AddressFamily";
import type { AddressFamilyPreference } from "./AddressFamilyPreference";

export type LinkRollup = { server_id: string, rtt_p50_ms: number | null, rtt_p95_ms: number | null, rtt_max_ms: number | null, uplink_loss_pct: number, downlink_loss_pct: number | null, worst_concealment_pct: number, datagrams_sent: bigint, datagrams_received: bigint, underruns: bigint, overflow_drops: bigint, ooo_drops: bigint, plc_frames: bigint, peer_count: number, samples: number, stalled_ticks: number, address_family: AddressFamily | null, family_preference: AddressFamilyPreference | null, protocol_version: string, client_version: string, };
