// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressFamily } from "./AddressFamily";
import type { LinkQuality } from "./LinkQuality";

export type LinkDiagnostics = { state: string, uptime_secs: bigint, rtt_ms: number | null, rtt_variance_ms: number | null, uplink_loss_pct: number, downlink_loss_pct: number | null, burst_loss_pct: number, worst_concealment_pct: number, jitter_buffer_ms: number, jitter_buffer_drops: bigint, quic_port: number | null, family: AddressFamily | null, paths_used: number, datagrams_dropped: bigint, stalled: boolean, quality: LinkQuality, };
