// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkDiagnostics } from "./LinkDiagnostics";
import type { LinkSample } from "./LinkSample";
import type { MicDiagnostics } from "./MicDiagnostics";
import type { PeerDiagnostics } from "./PeerDiagnostics";
import type { PlaybackDiagnostics } from "./PlaybackDiagnostics";
import type { SessionDiagnostics } from "./SessionDiagnostics";

export type LinkDiagnosticsSnapshot = { captured_at_ms: bigint, mic: MicDiagnostics, playback: PlaybackDiagnostics, link: LinkDiagnostics, session: SessionDiagnostics, peers: Array<PeerDiagnostics>, history: Array<LinkSample>, };
