// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkSample = { at_ms: bigint, rtt_ms: number | null, uplink_loss_pct: number, worst_concealment_pct: number, };
