// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Keypair } from "./Keypair";

export type LoginResponse = { gamerpic: string, gamertag: string, keypair: Keypair, signature: Keypair, certificate: string, certificate_key: string, certificate_ca: string, quic_connect_string: string, };
