// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MicDiagnostics = { device: string | null, sample_rate: number | null, gate_open: boolean, muted: boolean, datagrams_per_sec: number, };
