// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoiseGateStatus } from "./NoiseGateStatus";

export type MicDiagnostics = { device: string | null, sample_rate: number | null, noise_gate: NoiseGateStatus, muted: boolean, datagrams_per_sec: number, };
