// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mute event names emitted to the frontend via Tauri events.
 * The Display/to_string() of each variant is the full event name.
 */
export type MuteEvent = "mute:input" | "mute:output";
