// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoiseGateSettings = { open_threshold: number, close_threshold: number, release_rate: number, attack_rate: number, hold_time: number, };
