// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the noise gate is doing to this microphone, right now.
 *
 * Three states rather than a boolean, because a boolean could not distinguish the two
 * that matter most to someone whose microphone has gone quiet: a gate that is switched
 * off passes everything, and a gate that is open passes everything, so "is audio getting
 * through" reads identically for both. A reader could not tell whether the gate was even
 * attached, and the natural inference from a row saying `open` was that it was — which is
 * exactly the wrong place to go looking.
 */
export type NoiseGateStatus = "Disabled" | "Open" | "Closed";
