// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObservedCertificate = { subject: string, issuer: string, not_after: bigint, sans: Array<string>, };
