// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OnboardingState {
    welcome: boolean;
    microphone: boolean;
    notifications: boolean;
    devices: boolean;
}
