// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One participant's voice activity, as coarsely as a meter can be driven.
 *
 * Deliberately not a level. A level has to be resent whenever it changes, and speech changes
 * at syllable rate — so carrying one costs a message several times a second per person, on a
 * transport where the message count is the whole cost. These two fields change on the order of
 * once a phrase, and the client generates the motion between them.
 */
export type ParticipantLevel = { 
/**
 * Whether audio is passing right now: past the gate, not muted, above the floor.
 */
speaking: boolean, 
/**
 * How loud, in `0..=LOUDNESS_STEPS` steps of the meter's own decibel scale.
 *
 * Quantised so the emitter has something that stops changing. A float changes on every
 * frame and would put this back on the wire at capture rate.
 */
loudness: number, };
