// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerDiagnostics = { name: string, underruns: bigint, overflow_drops: bigint, ooo_drops: bigint, plc_frames: bigint, silence_frames: bigint, frames_decoded: bigint, ring_len: number, capacity: number, warmup_needed: number, quality_score: number, concealment_pct: number, buffer_ms: number, };
