// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";
import type { PermissionEntry } from "./PermissionEntry";

export type PermissionListResponse = { gamertag: string, game: Game, entries: Array<PermissionEntry>, };
