// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybackDiagnostics = { device: string | null, sample_rate: number | null, datagrams_per_sec: number, muted_peer_count: number, deafened: boolean, };
