// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the source of how a player was added to the player store
 * This enables multi-source tracking for proximity detection vs group membership
 */
export type PlayerSource = "Proximity" | "Group";
