// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerGainSettings } from "./PlayerGainSettings";
import type { PlayerKey } from "./PlayerKey";

/**
 * One stored row: who, where, and what you decided about them.
 *
 * The shape the Players settings pane consumes. The key stays whole here rather than being
 * flattened to a bare identity, because the pane lists rows across a server boundary the
 * mixer never sees — the mixer is handed an already-scoped projection instead.
 */
export type PlayerSettingsRow = { key: PlayerKey, settings: PlayerGainSettings, };
