// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerGainSettings } from "./PlayerGainSettings";

export type PlayerGainStore = { [key in string]: PlayerGainSettings };
