// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerGainSettings = { gain: number, muted: boolean, 
/**
 * Unix milliseconds when this player was last near you, absent for an entry written
 * before it was recorded.
 *
 * This store is already the list of players a device holds an opinion about, so stamping
 * it makes the same store answer "who have I been around lately" — which is what the
 * settings pane needs, with no second list to keep in step with this one.
 *
 * `f64` rather than `u64` because this store is written from TypeScript as well, and
 * ts-rs maps a `u64` to `bigint` — which `JSON.stringify` refuses, so every save would
 * throw. A double holds epoch milliseconds exactly for the next quarter of a million
 * years, and it is what `Date.now()` returns anyway.
 */
last_seen?: number | null, };
