// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one player's settings on one server.
 *
 * `cn` is the canonical `game:gamertag` — `minecraft:Alaydriem` — which is the certificate
 * CN the server stamps onto every packet. It is never a bare gamertag. A bare name does not
 * resolve, and an unresolved lookup reads as unity gain rather than as an error, so a keying
 * mistake is audible instead of a silent absence nobody can debug.
 *
 * The server is part of the key because a decision is about a person *here*. The same
 * gamertag on two servers is two rows, and muting them on one must not silence them on the
 * other.
 */
export type PlayerKey = { server: string, cn: string, };
