// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelativePosition } from "./RelativePosition";

/**
 * A complete picture of what the observer can see, not a delta.
 *
 * Each snapshot supersedes the last, so a dropped or delayed frame costs one
 * animation step rather than leaving the UI permanently wrong. Approach,
 * departure and steady state are derived client-side by diffing `name`
 * across consecutive snapshots.
 */
export type PositionSnapshot = { 
/**
 * Monotonic per-session counter; lets the client discard reordered frames.
 */
seq: bigint, positions: Array<RelativePosition>, };
