// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a player near you is on voice at all.
 *
 * Somebody in the world without BVC is still worth drawing. They are standing in front of
 * you and nothing you say reaches them, which is the most common confusion a proximity
 * voice product produces — and omitting them from the feed makes them indistinguishable
 * from nobody being there.
 */
export type PresenceKind = "voice" | "game";
