// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether this client and a server speak the same protocol.
 *
 * Separate from reachability on purpose: a server can answer perfectly and still be
 * unusable, and "nothing at that address" and "that server speaks a different
 * protocol" send someone to entirely different places. Only major and minor are
 * compared — patch releases do not change the wire format.
 */
export type ProtocolCompatibility = { server_version: string, client_version: string, compatible: boolean, 
/**
 * True when the client is behind, which is the case an update can fix.
 */
client_too_old: boolean, };
