// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PTT state event emitted to the frontend via Tauri events.
 * The Display/to_string() of the variant is the event name.
 */
export type PttEvent = "ptt:active";
