// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnsweredVia } from "./AnsweredVia";

export type ReachabilityOutcome = { "state": "answered", via: AnsweredVia, rtt_micros: number, } | { "state": "no_route" } | { "state": "silent" };
