// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a reachability report means for a player about to commit to a server.
 *
 * Derived in one place so every surface that shows it — the login address field, the
 * server selector — reaches the same conclusion from the same evidence.
 *
 * A failed DNS lookup is deliberately not here: no report exists in that case, so it
 * surfaces as an error from the planner rather than as a verdict about a host that
 * was never contacted.
 */
export type ReachabilityVerdict = "Ready" | "VoiceFallback" | "VoiceBlocked" | "Unreachable" | "NoRoute";
