// This file was generated by [ts-rs](https://github.com/Alaydriem/ts-rs). Do not edit this file manually.

export interface RealmEntry {
    id: number;
    name: string;
    motd: string;
    state: string;
    owner_uuid: string;
}
