// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateReason } from "./GateReason";

export type RealmsGateStatus = { "status": "allowed", reason: GateReason, } | { "status": "feature_disabled" } | { "status": "not_entitled" };
