// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RealmEntry = { id: bigint, name: string, motd: string, state: string, owner_uuid: string, };
