// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionManifest } from "./SessionManifest";

export type RecordingSession = { session_data: SessionManifest, file_size_mb: number, recording_path: string, exportable: boolean, };
