// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackKind } from "./TrackKind";

export type RecordingTrack = { keys: Array<string>, display: string, kind: TrackKind, };
