// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RecordingSession {
  session_data: SessionData;
  file_size_mb: number;
  recording_path: string;
}

import type { SessionData } from './SessionData';