// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceKind } from "./PresenceKind";

/**
 * Another player's position expressed relative to an observer.
 *
 * Carries no absolute coordinate: a client learns that somebody is forty blocks to the
 * north-east, never where either of them is standing. What it does carry is who, because a
 * card needs a name and a distance needs somebody to belong to — and everyone in scope is
 * inside the observer's own visual range regardless.
 *
 * The server decides who appears, using the same per-game rule voice routing uses at feed
 * range, so world, relay world, dimension and spectator state are all already accounted
 * for by the time an entry exists.
 */
export type RelativePosition = { 
/**
 * The certificate CN form, `game:gamertag`, with the gamertag's own casing. It is the
 * identity channels, recordings and a player's colour all key on, and it is stable
 * across sessions — which is what lets a card survive a reconnect.
 */
name: string, presence: PresenceKind, 
/**
 * Bearing from the observer in degrees, 0-359, relative to their facing.
 */
bearing_deg: number, 
/**
 * Horizontal distance in blocks, rounded.
 */
distance: number, 
/**
 * Signed vertical offset in blocks, so the UI can distinguish someone
 * above or below from someone alongside.
 */
elevation: number, };
