// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceRoster } from "./VoiceRoster";

/**
 * Who this client can hear, as one push frame.
 */
export type RosterPush = { type: string, data: VoiceRoster, };
