// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressFamilyPreference } from "./AddressFamilyPreference";
import type { EndpointReachability } from "./EndpointReachability";
import type { ReachabilityVerdict } from "./ReachabilityVerdict";

export type ServerReachability = { host: string, quic: Array<EndpointReachability>, https: Array<EndpointReachability>, ws: Array<EndpointReachability>, preference: AddressFamilyPreference, verdict: ReachabilityVerdict, best_rtt_micros: number | null, fallback_rtt_micros: number | null, };
