// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressFamilyPreference } from "./AddressFamilyPreference";
import type { EndpointReachability } from "./EndpointReachability";

export type ServerReachability = { host: string, quic: Array<EndpointReachability>, https: Array<EndpointReachability>, preference: AddressFamilyPreference, };
