// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PlayerAudioConfig {
  sample_rate: number;
  channels: number;
}

export interface SessionData {
  session_id: string;
  start_timestamp: number;
  end_timestamp?: number;
  duration_ms?: number;
  emitter_player: string;
  participants: Array<string>;
  player_audio_configs: Record<string, PlayerAudioConfig>;
  created_at: string;
}