// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressFamilyPreference } from "./AddressFamilyPreference";

export type SessionDiagnostics = { server: string | null, protocol_version: string | null, proximity_range: number | null, falloff: string | null, family_preference: AddressFamilyPreference | null, };
