// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionManifest = { session_id: string, start_timestamp: bigint, end_timestamp: bigint | null, duration_ms: bigint | null, emitter_player: string, participants: Array<string>, created_at: string, };
