// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";
import type { PermissionEffect } from "./PermissionEffect";

export type SetPermissionRequest = { gamertag: string, game: Game, permission: string, effect: PermissionEffect, };
