// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpatialAudioConfig = { close_threshold: number, falloff_distance: number, steepen_start: number, deafen_distance: number, deafen_multiplier: number, panning_start: number, max_attenuation_db: number, };
