// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamConfig = { channels: number, sample_rate: number, sample_format: string, buffer_size_min: number, buffer_size_max: number, };
