// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a track is, which is what decides where it sits in the list and what it is called.
 */
export type TrackKind = "Own" | "Player" | "Jukebox";
