// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransferTargetResponse = { host: string, port: number, expires_at: bigint, };
