// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which transport is carrying a voice session.
 *
 * Every diagnostic, metric and error message that describes a link needs this: the two
 * transports have different latency characteristics and different failure modes, so a
 * measurement without it cannot be compared against another, and an error code that says
 * only "the voice link failed" cannot say which one did.
 */
export type TransportKind = "Quic" | "WebSocket";
