// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Emitted when the voice mode changes, whoever changed it.
 *
 * Settings, the Stream Deck and a future in-game command all write the same setting, and
 * the mic button is a hold control in one mode and a toggle in the other. Without this the
 * dashboard reads the mode once at start-up and keeps offering the wrong control.
 */
export type VoiceModeEvent = "voice-mode:changed";
