// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceMode } from "./VoiceMode";

/**
 * What the audio backend believes about this microphone, right now.
 *
 * Reported rather than inferred. Mute lives in a process-global flag on the capture
 * stream, the voice mode lives on the keybind listener, and the UI keeps its own copy of
 * both — so "the button says unmuted" is evidence about the third copy and nothing else.
 * In push-to-talk the button deliberately never draws the muted glyph, which leaves no
 * surface at all showing what the microphone is actually doing.
 */
export type VoiceRuntimeState = { voiceMode: VoiceMode, 
/**
 * Whether a push-to-talk hold is registered. Always false in open mic.
 */
pttActive: boolean, 
/**
 * The flag the capture stream reads. `true` means frames are zeroed at the source.
 */
inputMuted: boolean, outputMuted: boolean, };
