// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerSource } from "./PlayerSource";

/**
 * One person this client can hear.
 *
 * Membership is decided before a member reaches here: a name is present only while it holds a
 * live voice connection. A player known from the position feed alone — in the world, with no
 * BVC client — is not audible and never appears.
 */
export type VoiceMember = { 
/**
 * Canonical `game:gamertag`, the same key `LevelSnapshot.peers` uses.
 */
name: string, 
/**
 * Why this member is audible. Never empty, and both are possible at once.
 */
sources: Array<PlayerSource>, 
/**
 * Public avatar URL, absent until resolved or when the player has none.
 */
gamerpic: string | null, };
