// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceMember } from "./VoiceMember";

/**
 * Everyone this client can hear, as one frame.
 *
 * Keyed the same way `LevelSnapshot` keys its peers, because a consumer joins the two by name:
 * this frame decides which meters exist, and the level frame drives them.
 */
export type VoiceRoster = { 
/**
 * This client's own canonical identity. Never in `members`.
 */
own: string, members: Array<VoiceMember>, };
