// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebsocketTicketResponse = { ticket: string, 
/**
 * Seconds until expiry, so the caller can decide whether to reuse a held
 * ticket or fetch a fresh one before reconnecting.
 */
expires_in: bigint, };
