// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebSocketClientInfo = { id: string, name: string, route: string, connected_at: bigint, commands: number, };
