name: BedrockVoiceChat
version: ${version}
main: com.alaydriem.bedrockvoicechat.paper.PaperPlugin
api-version: "1.21"
description: Server-side player position tracking for proximity voice chat
authors:
  - Charles R. Portwood II (Alaydriem)
